import Head from 'next/head'
import Link from 'next/Link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Altruism through Actionable Tech
        </h1>

        <p className={styles.description}>
        Build The Change You Wish To See In The World
        </p>

        <div className={styles.grid}>
          <Link href="/equity" className={styles.card}>
            <div>
            <h2>Equity 🍏 &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
            </div>
          </Link>

          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Etherealism 🕊 &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Idealism 🥼 &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Diplomacy 📜 &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Altruism ☁️ &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Networks 🌸 &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          
        </div>
      </main>
    </div>
  )
}
